WIP -- Add fluentd chart
att-comdev/openstack-helm-addons pull request #12
Opened 2017-04-23 01:41 UTC by wilkers-steve

This provides a functional deployment of fluentd. It currently
requires a service named elasticsearch-logging to function
properly. This will require additional configuration as logging
needs evolve, but functions in its current state

2017-05-17 19:49 UTC, larryrensing requested changes

2017-05-17 19:49 UTC, larryrensing commented on fluentd/templates/daemonset-fluentd.yaml
> +      - name: tdagentconf
fluentd-etc

2017-05-17 19:49 UTC, larryrensing commented on fluentd/templates/daemonset-fluentd.yaml
> +      - name: startsh
fluentd-bin

2017-05-17 19:49 UTC, larryrensing commented on fluentd/templates/daemonset-fluentd.yaml
> +          readOnly: true
do we want volume overrides here?

2017-05-17 19:49 UTC, larryrensing commented on fluentd/templates/daemonset-fluentd.yaml
> +          name: fluentd-bin
and here?

2017-05-17 19:49 UTC, larryrensing commented on fluentd/Chart.yaml
> +version: 0.1.0
add remainder of chart metadata (home, sources, maintainers, ..)

2017-05-22 19:47 UTC, wilkers-steve commented on fluentd/templates/daemonset-fluentd.yaml
> +          readOnly: true
They're not appropriate here.  The only configuration file that needs to be mounted is td-agent.conf, and the only behavior we should support is the ability to override that file wholesale.

2017-06-16 04:19 UTC, alanmeadows commented
Steve, should this be closed as it is now destined for github.com/openstack?

2017-06-16 12:01 UTC, closed without merging