WIP - Add Kibana Chart
att-comdev/openstack-helm-addons pull request #13
Opened 2017-04-30 22:31 UTC by wilkers-steve

Adds a basic Kibana Chart for use with Elasticsearch and Fluentd

2017-05-17 19:53 UTC, larryrensing requested changes

2017-05-17 19:53 UTC, larryrensing commented on kibana/templates/deployment.yaml
> +      labels:
define an update strategy in here

2017-05-17 19:53 UTC, larryrensing commented on kibana/templates/service.yaml
> +    k8s-app: kibana-logging
perhaps add a way for someone to expose a nodeport?

2017-06-16 04:19 UTC, alanmeadows commented
Steve, should this be closed as it is now destined for github.com/openstack?

2017-06-16 12:00 UTC, wilkers-steve commented
@alanmeadows affirmative

2017-06-16 12:00 UTC, closed without merging